pipeline {
      agent { label 'rahulwinnode' }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/RahulBGuttedar/Amazon/Amazon.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project...'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
            }
        }
    }
}
